# Yarn Berry Configuration for MCP Gateway
# Optimized for Docker environments and CI/CD

enableTelemetry: false
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"

# Performance optimizations
enableImmutableInstalls: true
enableInlineBuilds: false
enableStrictSsl: true
enableNetwork: false
enableGlobalCache: false

# Cache configuration
cacheFolder: "./.yarn/cache"
enableMirror: true

# Security
enableScripts: true

# Build optimizations
preferInteractiveUpdates: false
progressMode: "compact"
