#!/usr/bin/env bash
# Check for Context Forge Docker image updates
# Compares current pinned version with latest release from IBM/mcp-context-forge

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# shellcheck source=scripts/lib/log.sh
source "${SCRIPT_DIR}/lib/log.sh"

GITHUB_REPO="IBM/mcp-context-forge"
CURRENT_VERSION=""
LATEST_VERSION=""
DOCKER_COMPOSE_FILE="${REPO_ROOT}/docker-compose.yml"

# Extract current version from docker-compose.yml
extract_current_version() {
    if [[ ! -f "${DOCKER_COMPOSE_FILE}" ]]; then
        log_err "docker-compose.yml not found"
        exit 1
    fi
    
    CURRENT_VERSION=$(grep -E "image: ghcr.io/ibm/mcp-context-forge:" "${DOCKER_COMPOSE_FILE}" | head -1 | sed -E 's/.*:([^ ]+).*/\1/')
    
    if [[ -z "${CURRENT_VERSION}" ]]; then
        log_err "Could not extract current version from docker-compose.yml"
        exit 1
    fi
    
    log_info "Current version: ${CURRENT_VERSION}"
}

# Fetch latest release from GitHub
fetch_latest_release() {
    log_info "Fetching latest release from ${GITHUB_REPO}..."
    
    local api_url="https://api.github.com/repos/${GITHUB_REPO}/releases/latest"
    local response
    
    response=$(curl -sf "${api_url}" -H "Accept: application/vnd.github.v3+json" 2>&1) || {
        log_err "Failed to fetch latest release from GitHub API"
        exit 1
    }
    
    LATEST_VERSION=$(echo "${response}" | grep -o '"tag_name": *"[^"]*"' | sed 's/"tag_name": *"\(.*\)"/\1/')
    
    if [[ -z "${LATEST_VERSION}" ]]; then
        log_err "Could not parse latest version from GitHub API response"
        exit 1
    fi
    
    log_info "Latest version: ${LATEST_VERSION}"
}

# Compare versions
compare_versions() {
    if [[ "${CURRENT_VERSION}" == "${LATEST_VERSION}" ]]; then
        log_ok "Already using latest version: ${CURRENT_VERSION}"
        echo "status=up-to-date" >> "${GITHUB_OUTPUT:-/dev/null}"
        return 0
    fi
    
    log_warn "Update available: ${CURRENT_VERSION} → ${LATEST_VERSION}"
    echo "status=update-available" >> "${GITHUB_OUTPUT:-/dev/null}"
    echo "current_version=${CURRENT_VERSION}" >> "${GITHUB_OUTPUT:-/dev/null}"
    echo "latest_version=${LATEST_VERSION}" >> "${GITHUB_OUTPUT:-/dev/null}"
    
    # Generate update report
    generate_update_report
    
    return 1
}

# Generate update report
generate_update_report() {
    local report_file="${REPO_ROOT}/docker-update-report.md"
    
    cat > "${report_file}" <<EOF
# Docker Image Update Available

## Context Forge Gateway

- **Current Version**: \`${CURRENT_VERSION}\`
- **Latest Version**: \`${LATEST_VERSION}\`
- **Image**: \`ghcr.io/ibm/mcp-context-forge:${LATEST_VERSION}\`

## Changes

View the full changelog at:
https://github.com/${GITHUB_REPO}/releases/tag/${LATEST_VERSION}

## Files to Update

1. \`docker-compose.yml\` - Update gateway image tag
2. \`scripts/cursor-mcp-wrapper.sh\` - Update wrapper image tag
3. \`.github/workflows/ci.yml\` - Update CI image references
4. \`Makefile\` - Update cursor-pull target
5. \`README.md\` - Update version references
6. \`docs/DEVELOPMENT.md\` - Update version references

## Testing Checklist

- [ ] Run \`make stop\` to stop current stack
- [ ] Update image tags in files listed above
- [ ] Run \`make start\` to start with new version
- [ ] Run \`make register\` to verify gateway registration
- [ ] Run \`make verify-cursor-setup\` to verify Cursor integration
- [ ] Run \`make lint\` and \`make test\` to verify CI checks
- [ ] Test Cursor connection with wrapper

---

*This report was automatically generated by the Docker update checker.*
EOF
    
    log_ok "Update report generated: ${report_file}"
}

# Main execution
main() {
    log_step "Checking for Context Forge Docker image updates"
    
    extract_current_version
    fetch_latest_release
    compare_versions
}

main "$@"
