#!/usr/bin/env python3
"""
Interactive Configuration Wizard for MCP Gateway

Phase 3: Command Simplification
Provides an interactive setup experience to reduce command complexity.
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Any
import inquirer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

class ConfigWizard:
    """Interactive configuration wizard for MCP Gateway setup."""

    def __init__(self):
        self.repo_root = Path(__file__).parent.parent
        self.env_file = self.repo_root / ".env"
        self.config = {}
        self.load_existing_config()

    def load_existing_config(self):
        """Load existing configuration from .env file."""
        if self.env_file.exists():
            with open(self.env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        self.config[key] = value

    def save_config(self):
        """Save configuration to .env file."""
        with open(self.env_file, 'w') as f:
            f.write("# MCP Gateway Configuration\n")
            f.write("# Generated by interactive configuration wizard\n\n")

            for key, value in sorted(self.config.items()):
                f.write(f"{key}={value}\n")

    def check_prerequisites(self) -> bool:
        """Check if prerequisites are installed."""
        console.print("[bold blue]Checking prerequisites...[/bold blue]")

        prerequisites = {
            "docker": "Docker",
            "docker-compose": "Docker Compose",
            "python3": "Python 3",
            "npm": "Node.js/npm"
        }

        missing = []
        for cmd, name in prerequisites.items():
            try:
                subprocess.run([cmd, "--version"], capture_output=True, check=True)
                console.print(f"  ✅ {name}")
            except (subprocess.CalledProcessError, FileNotFoundError):
                console.print(f"  ❌ {name} - [red]missing[/red]")
                missing.append(name)

        if missing:
            console.print(f"\n[red]Missing prerequisites: {', '.join(missing)}[/red]")
            console.print("Please install missing tools and run the wizard again.")
            return False

        console.print("[green]✅ All prerequisites installed[/green]\n")
        return True

    def setup_secrets(self):
        """Setup or validate JWT and encryption secrets."""
        console.print("[bold blue]Setting up security secrets...[/bold blue]")

        secrets = {
            "JWT_SECRET_KEY": "JWT secret key (min 32 characters)",
            "AUTH_ENCRYPTION_SECRET": "Encryption secret (min 32 characters)",
            "PLATFORM_ADMIN_EMAIL": "Admin email for JWT tokens"
        }

        for secret, description in secrets.items():
            current_value = self.config.get(secret, "")

            if secret.endswith("_SECRET"):
                if current_value and len(current_value) >= 32:
                    console.print(f"  ✅ {description}: [green]Already configured[/green]")
                else:
                    console.print(f"  🔄 {description}: [yellow]Generating new secret...[/yellow]")
                    if secret == "JWT_SECRET_KEY":
                        new_secret = subprocess.check_output(
                            ["openssl", "rand", "-base64", "32"],
                            text=True
                        ).strip()
                    else:
                        new_secret = subprocess.check_output(
                            ["openssl", "rand", "-base64", "32"],
                            text=True
                        ).strip()
                    self.config[secret] = new_secret
                    console.print(f"  ✅ {description}: [green]Generated[/green]")
            else:
                if current_value:
                    console.print(f"  ✅ {description}: [green]{current_value}[/green]")
                    if not inquirer.confirm(f"Keep current email: {current_value}?"):
                        new_email = inquirer.text("Enter admin email:", default=current_value)
                        self.config[secret] = new_email
                else:
                    new_email = inquirer.text("Enter admin email:")
                    self.config[secret] = new_email
                    console.print(f"  ✅ {description}: [green]{new_email}[/green]")

        console.print()

    def configure_ide_setup(self):
        """Interactive IDE configuration setup."""
        console.print("[bold blue]IDE Configuration Setup[/bold blue]")

        if not inquirer.confirm("Would you like to configure IDE connections now?"):
            return

        # Detect installed IDEs
        ides_detected = self.detect_ides()

        if not ides_detected:
            console.print("[yellow]No IDEs detected. You can configure them later with 'make ide-setup'.[/yellow]")
            return

        console.print(f"Detected IDEs: {', '.join(ides_detected)}")

        # Select IDEs to configure
        selected_ides = inquirer.checkbox(
            "Select IDEs to configure:",
            choices=ides_detected + ["all"],
            default=["all"] if "all" in ides_detected else ides_detected
        )

        if "all" in selected_ides:
            selected_ides = ["cursor", "windsurf", "vscode", "claude"]

        # Configure each selected IDE
        for ide in selected_ides:
            console.print(f"\nConfiguring {ide}...")
            try:
                result = subprocess.run(
                    ["python3", "scripts/ide-setup.py", "setup", ide, "--action", "install"],
                    cwd=self.repo_root,
                    capture_output=True,
                    text=True
                )
                if result.returncode == 0:
                    console.print(f"  ✅ {ide}: [green]Configuration installed[/green]")
                else:
                    console.print(f"  ❌ {ide}: [red]Failed to install[/red]")
                    console.print(f"     Error: {result.stderr}")
            except Exception as e:
                console.print(f"  ❌ {ide}: [red]Error: {e}[/red]")

        console.print()

    def detect_ides(self) -> List[str]:
        """Detect installed IDEs."""
        ides = []
        home = Path.home()

        # Check Cursor
        if (home / ".cursor").exists():
            ides.append("cursor")

        # Check VSCode
        if (home / ".vscode").exists() or (home / ".config" / "Code" ).exists():
            ides.append("vscode")

        # Check Windsurf
        if (home / ".windsurf").exists():
            ides.append("windsurf")

        # Check Claude Desktop
        if (home / ".config" / "claude").exists():
            ides.append("claude")

        return ides

    def configure_services(self):
        """Configure which services to run."""
        console.print("[bold blue]Service Configuration[/bold blue]")

        # Read current services configuration
        services_file = self.repo_root / "config" / "services.yml"
        if services_file.exists():
            try:
                with open(services_file, 'r') as f:
                    services_config = yaml.safe_load(f)

                console.print("Current services configuration:")
                for service, config in services_config.get('services', {}).items():
                    enabled = config.get('enabled', True)
                    status = "✅ Enabled" if enabled else "❌ Disabled"
                    console.print(f"  {service}: {status}")

                if not inquirer.confirm("Would you like to modify service configuration?"):
                    return

                # Let user select services to enable/disable
                services = list(services_config.get('services', {}).keys())
                selected_services = inquirer.checkbox(
                    "Select services to enable:",
                    choices=services,
                    default=[s for s, c in services_config.get('services', {}).items()
                           if c.get('enabled', True)]
                )

                # Update configuration
                for service in services:
                    if service in services_config['services']:
                        services_config['services'][service]['enabled'] = service in selected_services

                # Save updated configuration
                with open(services_file, 'w') as f:
                    yaml.safe_dump(services_config, f, default_flow_style=False)

                console.print("[green]✅ Service configuration updated[/green]")

            except Exception as e:
                console.print(f"[red]Error reading services configuration: {e}[/red]")

        console.print()

    def setup_development_environment(self):
        """Setup development environment."""
        console.print("[bold blue]Development Environment Setup[/bold blue]")

        if not inquirer.confirm("Would you like to set up the development environment?"):
            return

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console
        ) as progress:

            # Install pre-commit hooks
            task = progress.add_task("Installing pre-commit hooks...", total=None)
            try:
                subprocess.run(["make", "pre-commit-install"], cwd=self.repo_root, check=True)
                progress.update(task, description="✅ Pre-commit hooks installed")
            except subprocess.CalledProcessError:
                progress.update(task, description="❌ Failed to install pre-commit hooks")

            # Install Node.js dependencies
            task = progress.add_task("Installing Node.js dependencies...", total=None)
            if (self.repo_root / "package.json").exists():
                try:
                    subprocess.run(["npm", "install"], cwd=self.repo_root, check=True)
                    progress.update(task, description="✅ Node.js dependencies installed")
                except subprocess.CalledProcessError:
                    progress.update(task, description="❌ Failed to install Node.js dependencies")
            else:
                progress.update(task, description="⏭️ No Node.js dependencies found")

            # Install Python dependencies
            task = progress.add_task("Installing Python dependencies...", total=None)
            if (self.repo_root / "requirements.txt").exists():
                try:
                    subprocess.run(["pip3", "install", "-r", "requirements.txt"], cwd=self.repo_root, check=True)
                    progress.update(task, description="✅ Python dependencies installed")
                except subprocess.CalledProcessError:
                    progress.update(task, description="❌ Failed to install Python dependencies")
            else:
                progress.update(task, description="⏭️ No Python dependencies found")

        console.print("[green]✅ Development environment setup complete[/green]\n")

    def show_summary(self):
        """Show configuration summary and next steps."""
        console.print("[bold blue]Configuration Summary[/bold blue]")

        table = Table(title="Current Configuration")
        table.add_column("Setting", style="cyan")
        table.add_column("Value", style="green")

        # Show key configuration items
        key_settings = {
            "JWT_SECRET_KEY": "✅ Configured" if self.config.get("JWT_SECRET_KEY") else "❌ Missing",
            "AUTH_ENCRYPTION_SECRET": "✅ Configured" if self.config.get("AUTH_ENCRYPTION_SECRET") else "❌ Missing",
            "PLATFORM_ADMIN_EMAIL": self.config.get("PLATFORM_ADMIN_EMAIL", "Not set"),
            "IDE Configurations": "✅ Setup complete" if self.detect_ides() else "⏭️ Skipped"
        }

        for setting, value in key_settings.items():
            table.add_row(setting, value)

        console.print(table)

        console.print("\n[bold blue]Next Steps[/bold blue]")
        console.print("1. [green]make start[/green] - Start the gateway stack")
        console.print("2. [green]make register[/green] - Register gateways and virtual servers")
        console.print("3. [green]make jwt[/green] - Generate JWT token for API access")
        console.print("4. [green]make status[/green] - Check system status")
        console.print("5. [green]make ide-setup IDE=all[/green] - Configure IDE connections (if not done)")

        console.print("\n[bold blue]Useful Commands[/bold blue]")
        console.print("• [green]make help[/green] - Show contextual help with examples")
        console.print("• [green]make help-examples[/green] - Show practical examples")
        console.print("• [green]make status --detailed[/green] - Detailed system status")
        console.print("• [green]make list-servers[/green] - List virtual servers")

        console.print("\n[green]🎉 Configuration wizard complete![/green]")

    def run(self):
        """Run the interactive configuration wizard."""
        console.print(Panel.fit(
            "[bold blue]MCP Gateway Interactive Configuration Wizard[/bold blue]\n\n"
            "This wizard will help you configure your MCP Gateway setup.\n"
            "It will guide you through security setup, IDE configuration,\n"
            "service management, and development environment setup.",
            title="Welcome"
        ))

        try:
            # Check prerequisites
            if not self.check_prerequisites():
                return

            # Setup secrets
            self.setup_secrets()

            # Configure IDEs
            self.configure_ide_setup()

            # Configure services
            try:
                import yaml
                self.configure_services()
            except ImportError:
                console.print("[yellow]PyYAML not installed, skipping service configuration[/yellow]")

            # Setup development environment
            self.setup_development_environment()

            # Save configuration
            self.save_config()
            console.print("[green]✅ Configuration saved to .env file[/green]\n")

            # Show summary
            self.show_summary()

        except KeyboardInterrupt:
            console.print("\n[yellow]Wizard cancelled by user[/yellow]")
        except Exception as e:
            console.print(f"\n[red]Error during wizard: {e}[/red]")
            console.print("Please check the error above and try again.")

def main():
    """Main entry point."""
    wizard = ConfigWizard()
    wizard.run()

if __name__ == "__main__":
    main()
